### ISSUE TITLE
Binary Serialization

### ISSUE THREAD

**Issue by ugurcansoruc** [koszeggy/KGySoft.CoreLibraries#11]
Hello, how do I deserialize a data structure in c++ that I serialized using the BinarySerializer.Serialize. Thanks

**Comment by koszeggy** [comment]
`BinarySerializer` isn't really meant for interop. Its `Serialize` method uses the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) class internally, which has special treatment for a sort of directly supported .NET types, whereas performs recursive deep serialization as a fallback, relying on the .NET infrastructure such as the `ISerializable` interface or even private field names. Therefore the produced binary stream is not particularly useful in an unmanaged environment.

However, if you use [managed C++](https://learn.microsoft.com/en-us/cpp/dotnet/managed-types-cpp-cli) you can use the serializer just like any other .NET component. Please note though that it will deserialize managed .NET types only. And to be honest binary serialization is not quite recommended between endpoints in different environments because of compatibility and [security](https://stackoverflow.com/questions/20990724/binaryformatter-deserialise-malicious-code/67107584#67107584) problems (see also the warnings at the **Remarks** section of the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) class).

You didn't provide any examples but if you just want to map C# and C++ structures to each other, it might be better using the [`Marshal.StructureToPtr`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.structuretoptr) method that recognizes the possible [`MarshalAs`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshalasattribute) attributes on members that can be used to control the marshaling for possible non-blittable members. In fact, the [`BinarySerializer.SerializeValueType`](https://docs.kgysoft.net/corelibraries/html/M_KGySoft_Serialization_Binary_BinarySerializer_SerializeValueType.htm) method uses marshaling but only as a fallback, if the struct to serialize contains references, so again, it is not really meant for interop.

But for complex types, especially with nested classes or collections using some some text-based contracts (eg. XML or JSON messages or files) might be a better choice.

**Comment by ugurcansoruc** [comment]
First of all, thank you for your answer.

I used BinarySerializer in C#. I tried to deserialize the byte output of the struct it serialized in c++, but the static cast operations didn't work. This was a quick try, I thought maybe it could be, but the bytes didn't match. :) Then I gave up.

I'm currently trying to transfer an object from the C# .NET platform to any C++ environment. (Using socket communication.) Maybe The object can be in a nested structure. It can contain static or dynamic data structures. There have been studies that I have done using binary formatter and marshal before, but they do not offer a suitable use for the current situation. (I could use marshal very easily in non-nested structures. I also used binary formatter for dynamic data recording to the file.)

I'm trying not to use text-based serialization methods because I'm communicating over a socket. Serialized data size increases a lot when data structures get a bigger.

I used protocol buffers etc. as a solution to this problem before. But that's not exactly the solution I'm looking for. What would you suggest I do at this point?

**Comment by koszeggy** [comment]
> I used BinarySerializer in C#. I tried to deserialize the byte output of the struct it serialized in c++, but the static cast operations didn't work.

It _might_ work if you use [`BinarySerializer.SerializeValueType`](https://docs.kgysoft.net/corelibraries/html/M_KGySoft_Serialization_Binary_BinarySerializer_SerializeValueType.htm) and when both C# and C++ structs have the same size and field [alignment](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack).

> The object can be in a nested structure. [...] What would you suggest I do at this point?

If you cannot use CLR types (and thus the `BinarySerializer`) from the C++ side I would go for custom serialization. Protocol buffers may be one possible choice, or you can do everything by yourself at low level (C# side: `BinaryWriter`). But bear in mind that custom binary serialization is a very hard thing to debug if there is any single mismatch anywhere between the reader/writer sides inside of a deep nested structure.

So I think that the best compromise is maybe some JSON serialization, which is still much more compact than some XML-based messaging and can be debugged much more easily. There are many popular JSON libraries that are also serializers. Or if you prefer producing the messages manually you can also try my JSON [library](https://github.com/koszeggy/KGySoft.Json) (at least at the C# side).
