### ISSUE TITLE
'Unexpected type "XXX" in assembly...'

### ISSUE THREAD

**Issue by Audionysos** [koszeggy/KGySoft.CoreLibraries#12]
So, I'm trying the default minimal code from your example to serialize `MyClass` back and forward. The serialization passes, however on deserialization I've got exception cited in the title.
I just want to make sure that I understand this correctly - Do I actually need to explicitly write all the types used in `MyClass` structure, or write custom code which does it? That sounds insane. Why do you need that if I already gave the `MyClass`  to `Deserialize()` method? Shouldn't all types used within `MyClass` be expected implicitly? 
I understand that there are cases like having interface properties `ISomething xxx` where you would want me to specify that a `ConcreteSomething` could be used but I don't have that in my case. I have ~18 custom types used in `MyClass` already and I consider it a very trivial  structure... Do you really want me to type `typeof(XXX),...`  for all those types as method's parameters?

**Comment by koszeggy** [comment]
Thank you for your report.

What you experience is the consequence of the `SafeMode` breaking change introduced in v8.0.0. Before that it was enough to preload every assembly that contained the types referred by the serialization stream but unfortunately it wasn't safe enough.

If you are sure the deserialization stream is from a safe source (eg. you use it on a cryptographically secured channel), then the simplest solution is just to disable the `SafeMode` option in the `BinarySerializationFormatter` constructor, which is enabled by default starting with v8.0.0.

> Do I actually need to explicitly write all the types used in `MyClass` structure, or write custom code which does it?

In general, yes, but only in safe mode, only for types that are not supported natively, and only if you rely on the fallback `IFormatter` recursive serialization (the classic `BinaryFormatter` way). But when doing so, all of the custom types, including apparently innocent ones such as enums must be explicitly named as expected types. Its reason is explained in the description of [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm).

> Shouldn't all types used within `MyClass` be expected implicitly?

Not necessarily. If you implement `ISerializable` you can add totally custom types to the `SerializationInfo` so your wrapped types don't even need to be serializable ones. But even when relying on the default field-based serialization you can have `[NonSerialized]` fields, or fields with non-sealed types that can hold any derived type.

> I have ~18 custom types used in `MyClass` already and I consider it a very trivial structure... Do you really want me to type `typeof(XXX),...` for all those types as method's parameters?

I understand it can be frustrating. But actually there are some possible solutions:
* If every nested type is serialized recursively by fields (they are just `[Serializable]` types with no customization) you can simply write an `ExtractTypes` method that does this for you (let me know if you want this feature in the libraries so I can include such an API in the next version). Please note that it may include a lot of unnecessary types if you have a field of a natively supported type (eg. even a simple `Dictionary<TKey, TValue>` has a few nested types that are not meant to be serialized).
* Or, implement `ISerializable`, and in the `GetObjectData` method use only natively supported types. Eg. add ints instead of enums, or add the properties of nested custom types as a `Dictionary<string, object>` (a ProtoBuf-like solution). And if some nested types are simple structs without references, just add their content as a byte array retrieved by the [`SerializeValueType<T>`](https://docs.kgysoft.net/corelibraries/html/M_KGySoft_Serialization_Binary_BinarySerializer_SerializeValueType__1.htm) method. Of course in the special constructor you should read these simple types to restore the original content.
* As the _Tip_ suggest above the last example of the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) page, you can implement [`IBinarySerializable`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_IBinarySerializable.htm), which provides an even more compact result than the default `IFormatter` graph. See the example for a pattern for more complex polymorphic cases.
* And as I mentioned above, you can simply disable `SafeMode`. But do it only if it really can be justified.

Please note that the first two bullet points refer to the classic `IFormatter`-ways. In the upcoming .NET versions the rest of the binary serialization-related types might be obsoleted as well, maybe even the `[Serializable]` attribute itself.

**Comment by Audionysos** [comment]
Yea, I've actually wanted to ask you about this before even trying your lib, because I've seen your posts on the safety topic all over the internet... :) 
I've read all those articles recently but I'm still not sure about it/not convinced.
See, I designed my data as simple as possible because I knew I will have to serialize it and I knew from the previous experience that it is pain in a butt. I've actually even wrote my own generic binary serializer back in the day but since I didn't have it under my hand I decided to try something new and then I've read  that it's not safe: https://learn.microsoft.com/en-gb/dotnet/standard/serialization/binaryformatter-security-guide 

So I've tried to use the `JsonSerializer` as advised  in the article and it works with `MyClass` back and forward without any customization - apparat form setting options object I just simply call `Serialize(myObject)` and `Deserialize<MyClass>(string)`. However I have [other issues with](https://stackoverflow.com/questions/77629944/can-i-force-system-text-json-jsonserializer-to-work-non-recursively/77632472?noredirect=1#77632472) `JsonSerializer` so I don't want to use it...

Anyway, my point is that if the `JsonSerializer` is considered "safe" (according to the article linked above) and is able to correctly deserialize `MyClass` given only a single type as parameter, then either a binary serializer can do this as well, or the `JsonSerializer` is not actually safe.

I've read the documentation you've linked (by the way, this is the best documentation I've read since I stopped programming in AS3, are you trying to beat Adobe in this? You are on good track... :) and it says:

>It's because though enums themselves are harmless, their type must be resolved just like any other type so a manipulated serialization stream may contain some altered type identity that could be resolved to a harmful type.

Could you elaborate on this? What kind of magic type resolving techniques the `JsonSerializer` uses that cannot be used in a binary serializer, and only the former is considered safe?

>But even when relying on the default field-based serialization you can have [NonSerialized] fields, or fields with non-sealed types that can hold any derived type.

Yes, but I'm talking about the types that are suppose to be serialized. If a field is not serialized that means it's also not deserialized, so you don't even need to know it's type and I don't need to specify it as "expected" neither. Where is the problem?

 And In case of derived type, if somewhere in `MyClass` there is field `object x` and serialized data holds an object of class `Y` and the `Y` type is not used explicitly anywhere in `MyClass` structure then in such case yes, it would be reasonable to ask if it was expected. Otherwise a `Descerialize<MyClass>()` call should tell I know `MyClass` read me that. An if I know `MyClass` and know that it looks like:
```
public MyClass {
    Y x;
}
``` 
Imho it's not sane to assume I don't expect Y. And even If the `Y` is from third party library, I still already use (and trust) it in my code so there should be no risk of executing unwanted code, right? 

Here we come to point where I would like to clarify about what "safety" we are talking about. Because I see the term is used very widely and vaguely on this topic while there is essential difference between "safe" and "safe". I would like to divide this into different kind of threats because I'm still confused as I'm trying to make correct decision: 
1. Execution - an attacker may execute his own malicious code on machine on which the data is been deserialized.
2. Abuse - an attacker may intentionally craft the input for deserialization (without executing his own code) causing: 
2.1 Harm user's system - such as with the `TempFiles` class.
2.2 Harm the application - crash/stall or simply hit performance.
4. Corruption - serializer may load invalid data for types that are not prepared for serialization, leading to unspecified application states that are hard to debug.
5. Invalidation - an input may contain data that is not unsupported by the loading application or stored in different format. Leading to immediate crashes or input refusal.

A non critical application (such as mine) may only be concerned about point **1** and **2.1**. I don't really care I've been provided invalid data and the app crashes as log as it don't harm the system.

 I'm far from any kind of security expert so just correct me if I'm wrong, but assumption of expected classes (`Y`)  don't refers point **1** but only **2.1**.
The point **1** is only possible if both:
1. An attacker have planted his infected dll on the system (which may indicate the system is already compromised) 
2. Serializer allows to load the dll and infected type specified in the input.

Also if an attacker is able to place a dll anywhere on the computer, he may as well override a dll containing the `Y` type. So even If I explicitly specify for your serializer that I expect `Y` type, it will not prevent loading infected type, right?
Otherwise the user would need to explicitly place the dll somewhere where the the application could find it or install it in GAC and after that the attacker would need to convince the same user to download and load his malicious data using our program. This sounds unlikely scenario. I image if attacker is able to do such somersaults, he would be also able to execute his code without use of our serialized data, but again, I consider myself as security noob...

As for **2.1** the scenario would be:
1. Someone writes some potentially vulnerable type in some library.
2. The library user is unaware of the vulnerability and/or uses it implicitly.
3. A serializer is unaware of this type as well.
4. An attacker is aware of the vulnerability.
5. Attacker finds an use case which benefits him in some way.
6. Attacker somehow tricks the user to load the data.

Again, I would consider much more likely that someone will rob my house tonight, as I sleep then this would ever happen in real life. Like the example with `TempFiles` (this is really the one one I know) - what exactly do you gain by deleting someone files? I bet some peoples deleted their files accidentally with this type without even using any kind o serializer at all... and probably no one did this maliciously. 

Anyway, the **2.1** still applies to `JsonSerializer` as well and also if the a programmer is unaware that the type `Y` is vulnerable he will specify it as "expected" anyway. So I'm still not sure what is the point of that? 

> (eg. even a simple Dictionary<TKey, TValue> has a few nested types that are not meant to be serialized).

Which ones? I see they are all marked as `Serializable`. I've seen your [discussion I believe here](https://github.com/dotnet/runtime/issues/50909) where the other guy told you It's not safe to serialize but I still struggle to understand what is the problem with it?

**Comment by koszeggy** [comment]
> So I've tried to use the `JsonSerializer` as advised in the article and it works with `MyClass` back and forward without any customization - apparat form setting options object I just simply call `Serialize(myObject)` and `Deserialize<MyClass>(string)`.

It's because it works a bit differently; in fact, similarly to my [`XmlSerializer`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Xml_XmlSerializer.htm). I've rewritten the [online example](https://dotnetfiddle.net/68p4u1) to serialize and safely deserialize a `Person` class using some custom type internally. The XML/Json deserialization do not need to specify the internally used type because it's not even stored in the serialization stream. The the nested type was the same as the property type so it wasn't necessary to store it.

You can say that it's redundant for the binary serialization as well; however, it's not how it works. The binary serialization graph essentially contains name-type-instance entries (exposed by `SerializationInfo` if you implement `ISerializable`) and when we populate this info for the deserialization we must know the type of the entries in advance. They have nothing to do with field types at this point and maybe they aren't fields anyway. The actual deserialization then can be driven either by an `ISerializable` special constructor, a surrogate selector or if none of those apply - the default strategy tries to map them to fields.

> If somewhere in `MyClass` there is field `object x` and serialized data holds an object of class `Y` and the `Y` type is not used explicitly anywhere in `MyClass` structure then in such case yes, it would be reasonable to ask if it was expected.

As I said, it's totally understandable and _I lean towards to add this recursive discovery to the serializer_. I just noted that such a discovery can include a lot of unnecessary types in case of otherwise supported types, and I brought `Dictionary<TKey, TValue>` as an example (it has fields referencing its nested `Entry`, `KeyCollection` and `ValueCollection` types that will not appear in the stream). But of course, the discovery could apply some filtering rather than just blindly performing a full scan.

> Could you elaborate on this? What kind of magic type resolving techniques the `JsonSerializer` uses that cannot be used in a binary serializer, and only the former is considered safe?

The half of the answer comes from the fact that type identity is not stored in the Json (or XML) stream, see above. But if the property type is `object` and you store an enum in that, then the type identity must be stored and the same issue appears.

> Also if an attacker is able to place a dll anywhere on the computer, he may as well override a dll containing the `Y` type. So even If I explicitly specify for your serializer that I expect `Y` type, it will not prevent loading infected type, right?

Making a malicious type executed is just one possible attack. And let's do it differently: the attacker just places a .dll to be available with type `Z` whereas your serialization stream contains `Y`. Even if `Y` is just an enum, it's stored by it's assembly qualified name. The attacker manipulates the stream so that replaces your innocent `Y` to refer the dangerous `Z` instead. Of course, if `Y` was an enum, the serialization would fail in the end anyway but this doesn't matter if `Type.GetType(myAssemblyQualifiedTypeName)` happily resolved the manipulated identity, willingly loading any assemblies, executing their module initializers, etc. This what you can prevent by specifying `Y` as an expected type. If `Z` was not expected, we don't start to resolve it. But the attacker doesn't even need to place any malicious .dll to your machine. If the serialization stream is used between remote endpoints it can be manipulated using core CLR types to cause unresponsiveness, etc. 

> Here we come to point where I would like to clarify about what "safety" we are talking about. Because I see the term is used very widely and vaguely on this topic while there is essential difference between "safe" and "safe". I would like to divide this into different kind of threats because I'm still confused as I'm trying to make correct decision

I enlisted some of the possible attacks [in this SO answer](https://stackoverflow.com/a/67107584/5114784). It also explains why the core `Dictionary<TKey, TValue>` deserialization can be dangerous (hmm... maybe I need to update it because since then the `SafeMode` became safer 😁). This could be avoided if `Dictionary` (and every other type) validated the deserialized data as I recommend it in the last example of the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm)'s description.

I apologize if I didn't answer everything but I need to go now. :) I think the main message is that I plan do something to make the enlisting of expected types less painful.

**Comment by Audionysos** [comment]
Don't worry, I understand I touched a lot of points and I still greatly appreciate your responses. I don't expect you to address every single question I make :)

> You can say that it's redundant for the binary serialization as well; however, it's not how it works.

If we specifically talk about "the" binary serialization then sure. But I'm talking generally about serialization - there is noting preventing a binary serializer from working in the same fashion as the json/xml serializers. I'm just saying that because some people may think that binary serializers are just inherently unsafe and text format serializers are inherently safe, which is simply not true.

> I just noted that such a discovery can include a lot of unnecessary types in case of otherwise supported types, and I brought `Dictionary<TKey, TValue>` as an example (it has fields referencing its nested `Entry`, `KeyCollection` and `ValueCollection` types that will not appear in the stream). But of course, the discovery could apply some filtering rather than just blindly performing a full scan.

Yes, and this is why I would expect serialization library to do this for me - it knows the best which types are natively supported and which types are not used.

> The attacker manipulates the stream so that replaces your innocent `Y` to refer the dangerous `Z` instead. ... This what you can prevent by specifying `Y` as an expected type.

I understand this very sole reason why you have the expected types list. I didn't stated that you don't need this at all. I'm just saying that **explicit** listing doesn't give you any real benefit vs **implicit** in regards to safety.

> It also explains why the core `Dictionary<TKey, TValue>` deserialization can be dangerous

This is exactly why I would like to have types of threats be clearly specified. Described problem is only level **3** according to may classification. Which in my case simply mens "I don't care!". There may be applications that should consider level **3** or all levels as serious, but in case were I use a serializer for a game, taking any special security measures against an absurdly little chance that someone maliciously changes a game state to cause my app to crash on the user's computer with fake `OutOfMemeoryException` - absurd.

Saying this I still want to have security measures on other, serious threats but It's hard to figure out which on are really serious if you put the risk described above in the very same bag as malicious code execution, simply labeling the bag "not safe". You then compare this to [accepting and executing arbitrary .exe file on the server](https://github.com/dotnet/runtime/issues/29976#issuecomment-547077542), along the "json is human readable..." lines, not provide any alternative for deprecated "unsafe" API and wonder why people still use `BinaryFormatter` ... sorry for little rant, You are not the main addressee.

**Comment by koszeggy** [comment]
> there is noting preventing a binary serializer from working in the same fashion as the json/xml serializers.

Yes, _generally_ the same rules apply for both of them. But there can be nuances, and I told the reason why XML (Json) serializer don't need to specify the nested types as expected ones the case above: if the type of a public property is the type of the actual instance of the property, then the identity of the nested type is not stored in the stream because it can be inferred. But `IFormatter` graph entries are not necessarily tied to fields or properties so the type of the entries is always stored.

> I'm just saying that because some people may think that binary serializers are just inherently unsafe and text format serializers are inherently safe, which is simply not true.

I [agree](https://stackoverflow.com/a/76955010/5114784)

> Yes, and this is why I would expect serialization library to do this for me

I will definitely do something about it in the next release

> I didn't stated that you don't need this at all.

And I didn't state you had stated that. 😁 That was merely an explanation for your question, not an attempt to convince you about something.

> This is exactly why I would like to have types of threats be clearly specified. Described problem is only level 3 according to may classification. Which in my case simply mens "I don't care!".

Though `BinarySerializationOptions.SafeMode` simply takes every security concern under a common umbrella (leaving only the `AllowNonSerializableExpectedCustomTypes` option to relax it a bit) still there is the "I know it better" way for advanced users: If you disable the `SafeMode` option you can freely assign the [`Binder`](https://docs.kgysoft.net/corelibraries/html/P_KGySoft_Serialization_Binary_BinarySerializationFormatter_Binder.htm) and [`SurrogateSelector`](https://docs.kgysoft.net/corelibraries/html/P_KGySoft_Serialization_Binary_BinarySerializationFormatter_SurrogateSelector.htm) properties. The only reason they are not allowed to set in safe mode is that the serializer has no control over what they do so they can be used even to weaken the default strict safety rules. But it's true also in the other way around: you can do a really secure custom type resolving in a custom binder and you can validate every custom serialization entry by a surrogate selector, which can highly improve the security even for a `BinaryFormatter`.

> I use a serializer for a game

Maybe off-topic a bit but didn't you consider using a text-based serializer (eg, the [`XmlSerializer`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Xml_XmlSerializer.htm)) for that purpose? I always use that one for application or plugin/extension configurations. Even if you don't want to let your users to manipulate these files (maybe because they are not configuration but savegame files) it's really beneficial if you can edit them easily without the loaded app. You still can zip them if the size or easy accessibility would be a problem.

**Comment by koszeggy** [comment]
I [added](https://github.com/koszeggy/KGySoft.CoreLibraries/commit/8ebf01dfa216f9427395767077932635796de565) a new `ExtractExpectedTypes` API, it will be in the next release.

Please note that it helps only in the most trivial cases. In case polymorphism or custom serialization the result may not be complete.

**Comment by koszeggy** [comment]
Released in [v8.1.0](https://github.com/koszeggy/KGySoft.CoreLibraries/releases/tag/v8.1.0)
