### ISSUE TITLE
Error with v5.6.1 / x86 / .NET 8

### ISSUE THREAD

**Issue by tonyrichter** [koszeggy/KGySoft.CoreLibraries#14]
Hi,

we have a very specific problem with an older version of the Core Library and I hope there might be a solution to it.

**What is the problem?**
We have an older software that has been on .Net Framework 4.7.2 and we were using the BinarySerializer from the Kgysoft CoreLib v5.6.1.
Now our customer decided that the software should be brought up to current standards so we transferred it to .NET 8 and made all necessary changes so everything works.
However, when we now want to load data that is stored in a blob in a Sqlite DB and is serialized by Kgysoft Serializer we get the following error:
![image](https://github.com/user-attachments/assets/2dc30750-08a8-4548-be75-7cafc79c2768)
("System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt.")

**What we already tried or found out:**
1. When we use a later version of the Kgysoft Core Lib (starting at 6.0.0) everything seems to work fine, however some data is lost (I think it's about bigger data blobs that contain more than 70million data points of floats). We tried all major version and it's the same with all of them. Some data is lost which is unfortunately not accepted by our customer
2. When we use 64bit compilation everything works just fine even using the old library version 5.6.1. However we have other dependencies that require compiling for 32bit/x86 which makes this unfortunately not viable.

Is there any idea what we can do here?
What might cause that behaviour?
Are there any options we could set so the Initialization of the "BinarySerializationFormatter" is possible given the circumstances (.NET 8, 32bit, v5.6.1)?

Thanks in advance!

**Comment by koszeggy** [comment]
Thank you for your report.

The x86 issue was a known one, it was [fixed](https://github.com/koszeggy/KGySoft.CoreLibraries/issues/10) a couple of years ago in version 6.0.2.

And unfortunately in v6.0.0 there was also a [breaking change](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/31a30340795d36ba3df8bac99e6e6e153c76a8ba/KGySoft.CoreLibraries/changelog.txt#L798) in the stream format that must have been introduced for various reasons. That must be the reason why some data is not deserialized correctly with the latest version. Though I try to avoid such format changes whenever possible, please note that a new main version may have such changes (but since v6.0.0 the format didn't change and it won't change in v9.0.0 either).

**The solution** can be a one-time migration in the database: you need to deserialize the content using the old version (possibly from .NET Framework), and then you need to do the serialization again with the new version.

It can be a bit tricky as you might need to reference two different versions of the same library at the same time but actually this can be achieved by [extern aliases](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias).

Alternatively, you can use the old `BinaryFormatter` just for the time of the migration (maybe this is simpler if you don't want to bother with extern aliases):
1. In the old environment (v5.6.1, .NET Framework 4.7.2) deserialize the database and serialize its content again by `BinaryFormatter`
2. Upgrade the package version to the latest version (v8.3.0) and perform the opposite operation again: deserialize by `BinaryFormatter`, serialize again with the new version. For the least trouble it is recommended to do this still in .NET Framework 4.7.2 because in .NET Core/.NET a lot of old types are not serializable anymore (well, breaking changes at every side of the table...). Maybe it doesn't affect your case as it depends on the actual serialized types.
3. Check if deserialization with the new version still works. Please note that starting with version 8.0.0 `SafeMode` deserialization is enabled by default, and it's interpretation has been [changed](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/31a30340795d36ba3df8bac99e6e6e153c76a8ba/KGySoft.CoreLibraries/changelog.txt#L292) radically: from now on you must enlist all of the expected types in the new deserialization overloads explicitly that are encoded by assembly qualified names (basically every custom type that are not supported natively). If you use custom types wrapped into each other in a trivial way, then the [`ExtractExpectedTypes`](https://docs.kgysoft.net/corelibraries/html/M_KGySoft_Serialization_Binary_BinarySerializer_ExtractExpectedTypes__1.htm) method may be helpful. You still can turn off `SafeMode` but it is not recommended, especially if you deserialize from a database (see the security notes at the [`BinarySerializationFormatter`](https://docs.kgysoft.net/corelibraries/html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm) class).
4. Now change from .NET Framework to .NET 8 and test again whether everything is fine.

I hope this helps, and I apologize for the possible headaches caused by the format change.

**Comment by tonyrichter** [comment]
Thank you very much for the quick response!

With the information you provided we will find our way around this issue.

Thanks for your effort, we really like your library.
